name: Build EPG JSON

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download e.xml
      run: |
        curl -L https://raw.githubusercontent.com/880824/epg/main/e.xml -o e.xml

    - name: Install Python deps
      run: |
        pip install xmltodict

    - name: Generate epg.json
      run: |
        python3 generate_epg.py

    - name: Commit epg.json
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add epg/epg.json
        git commit -m "Update EPG JSON" || echo "No changes"
        git push
